### ISSUE TITLE
thrift bazel modules conflicts on macos m1

### ISSUE THREAD

**Issue by tongke6** [baidu/babylon#78]
Hello Babylon maintainers, our project uses BRPC and we encountered the following issue when compiling on the macOS M1 platform.

```
ERROR: /private/var/tmp/_bazel_distiller/bedaa68a8664d1b29e96b826d058247f/external/bazel_tools/tools/build_defs/repo/utils.bzl:120:15: An error occurred during the fetch of repository 'thrift~':
   Traceback (most recent call last):
        File "/private/var/tmp/_bazel_distiller/bedaa68a8664d1b29e96b826d058247f/external/bazel_tools/tools/build_defs/repo/http.bzl", line 148, column 26, in _http_archive_impl
                download_remote_files(ctx)
        File "/private/var/tmp/_bazel_distiller/bedaa68a8664d1b29e96b826d058247f/external/bazel_tools/tools/build_defs/repo/utils.bzl", line 120, column 15, in download_remote_files
                p.wait()
Error in wait: java.io.IOException: Error downloading [https://baidu.github.io/babylon/registry/modules/thrift/0.21.0/overlay/BUILD] to /private/var/tmp/_bazel_distiller/bedaa68a8664d1b29e96b826d058247f/external/thrift~/BUILD: /private/var/tmp/_bazel_distiller/bedaa68a8664d1b29e96b826d058247f/external/thrift~/BUILD (Is a directory)
```

The reason might be that the macOS file system is case-insensitive, and thrift has a 'build' directory that conflicts with the Bazel 'BUILD' file.

**Comment by tongke6** [comment]
The solution is simple: rename the 'BUILD' file to 'BUILD.bazel' to avoid the conflict.
I have already submitted this change to secretflow/bazel-registry: https://github.com/secretflow/bazel-registry/blob/fb47e8fc01eca238f2d3ed15b3d066450d91ec2f/modules/thrift/0.21.0/source.json#L10

If you agree, I would be happy to make the modification in Babylon's modules as well.

**Comment by oathdruid** [comment]
never try build on mac yet...

Contributions are always welcome.
